---
toc: true
---

```{r}
#| message: false
#| echo: false
library(tidyverse)
```


```{r}
#| echo: false
## Course specifics

slides_repo <- "https://mdogucu.github.io/stats67-wi26-slides/"
code_repo <- "https://mdogucu.github.io/stats67-wi26-starter-code/"
gradescope <- "https://www.gradescope.com/courses/1205064"
```


```{r}
#| echo: false
#| message: false
readr::read_csv(here::here("specific-content/schedule.csv")) |> 
  mutate(
    reading = if_else(
      is.na(reading), 
      paste0(fontawesome::fa("book", fill = "#e6ddd1")),
      paste0(
        "[", 
        fontawesome::fa("book"), 
        "]",
        "(specific-content/readings/", 
        reading, 
        ")"
        )
      ),
    slides = if_else(
      is.na(slides), 
      paste0(fontawesome::fa("laptop", fill = "#e6ddd1")),
      paste0(
        "[", 
        fontawesome::fa("laptop"), 
        "]",
        "(",
        slides_repo, 
        slides, 
        ")"
        )
      ),
      code = if_else(
      is.na(code), 
      paste0(fontawesome::fa("r-project", fill = "#e6ddd1")),
      paste0(
        "[", 
        fontawesome::fa("r-project"), 
        "]",
        "(",
        code_repo, 
        code, 
        ")"
        )
      ),
      assessment = if_else(
      is.na(assessment), 
      paste0(fontawesome::fa("list-check", fill = "#e6ddd1")),
      paste0(
        "[", 
        fontawesome::fa("list-check"), 
        "]",
        "(",
        gradescope, 
        assessment, 
        ")"
        )
      ),
     other = if_else(
      is.na(other), 
      paste0(fontawesome::fa("note-sticky", fill = "#e6ddd1")),
      paste0(
        "[", 
        fontawesome::fa("note-sticky"), 
        "]",
        "(",
        other, 
        ")"
        )
      ),
  ) |> 
  knitr::kable() 
```


```{r}
#| echo: false
#| message: false
readr::read_csv(here::here("specific-content/schedule.csv")) |> 
  mutate(
    reading = if_else(is.na(reading), 
                      paste0(fontawesome::fa("book", fill = "#e6ddd1")),
  paste0(
    "[", fontawesome::fa("book"), "]",
    "(specific-content/readings/", reading, ")"
  ))) |> 
  knitr::kable() 
```

